export const PRODUCT_CATEGORIES_LOADING = 'PRODUCT_CATEGORIES_LOADING';
export const PRODUCT_CATEGORIES_SUCCESSFULLY = 'PRODUCT_CATEGORIES_SUCCESSFULLY';
export const PRODUCT_CATEGORIES_FAILD = 'PRODUCT_CATEGORIES_FAILD';